### PR TITLE
[DevOps] Github Action - Automatize test runner at merge

### LINKED ISSUE #68: [DevOps] Github Action - Automatize test runner at merge
**Description**
---
As Carbonable, we want to use Github action to launch tests during CI/CD when we merge on main.  CI should fail if all tests don't pass.

**Additional context**
---
[ Medium/Low Difficulty  - Cairo/DevOps - Medium Priority]

**Acceptance Criteria**
---
- [ ]  Implement Github Action to launch tests through a script in bash.
- [ ]  If some test fails, CI should fail and a message should explain which test crashed.
- [ ]  Config to trigger this Github action only when PR are merged in Main branch

### PR DESCRIPTION
**Pull request by lindsaymoralesb**
# Solves
closes #68  

# Description

As Carbonable, we want to use Github action to launch tests during CI/CD when we merge on main. CI should fail if all tests don't pass.

# Acceptance Criteria
- [X] Implement Github Action to launch tests through a script in bash.
- [X] If some test fails, CI should fail and a message should explain which test crashed.
- [X] Config to trigger this Github action only when PR are merged in Main branch

# Solution

A new GitHub action workflow was added to the repo. It was configured to be triggered on PR merged to main.
The workflow steps include:

1. The Scarb Setup with version 2.5.4
2. The snfoundry setup with version 0.18.0
3. Run the tests (scarb test)
4. Extract the statistics from the tests output (total passed tests, failed, skipped, etc) to display them in a more user friendly way, instead the whole test output.
5. If one or more tests failed, display which one(s) have an error and the CI fails.

# Examples

Test failed:
Screenshot 2024-06-25 at 13 40 24

Success:
Screenshot 2024-06-25 at 13 57 30

### CODE REVIEW

**Review by julienbrs — CHANGES_REQUESTED** [review]
It's super clear and really what we were expecting, congrats!
Could you please create a bash script and put all the logic of the `Run Cairo tests` step inside it?

Moreover, could you please add a badge in the readme saying "X tests" have passed? Would be a great visual addition

**Comment by lindsaymoralesb** [comment]
Thank you @julienbrs !!
Already extracted the logic of the step into a bash script.

Regarding the readme task, so would you want the gh action to automatically update the readme file just with the number of passed tests? And is [this](https://img.shields.io/badge/Tests-Passed-brightgreen) the badge you are referring to?

**Comment by julienbrs** [comment]
> Thank you @julienbrs !! Already extracted the logic of the step into a bash script.
> 
> Regarding the readme task, so would you want the gh action to automatically update the readme file just with the number of passed tests? And is [this](https://img.shields.io/badge/Tests-Passed-brightgreen) the badge you are referring to?

Yes indeed, update the readme automatically. You can either put the badge you just linked, or a badge where it's written the number of tests that passed (that's kinda the same, it's just to have a cool UI badge for it)

**Comment by lindsaymoralesb** [comment]
> Yes indeed, update the readme automatically. You can either put the badge you just linked, or a badge where it's written the number of tests that passed (that's kinda the same, it's just to have a cool UI badge for it)

Got it! Will update the PR in a few, and let you know once it's ready.

**Comment by lindsaymoralesb** [comment]
@julienbrs The comments are fully implemented now! Please review!

Below you will find an screenshot of how the badge would appear in the readme. Please let me know if I should make any changes.

Screenshot 2024-06-28 at 18 13 58

**Review by julienbrs — APPROVED** [review]
LGTM, I just changed the location of the badge in the readme. Congrats for your PR, really nice and clean work!

**Comment by julienbrs** [comment]
@all-contributors add @lindsaymoralesb for code and that great contrib! :heart_hands: :seedling:

**Comment by lindsaymoralesb** [comment]
> LGTM, I just changed the location of the badge in the readme. Congrats for your PR, really nice and clean work!

Thank you!! Hope to contribute again to this amazing project.

Btw, I just noticed the workflow failed on the last step (committing the readme update). Please make sure to update the workflow permissions under the project settings. Go to actions and it should have read and write selected. @julienbrs 

image

**Pull request merged**
