### PR TITLE
Added starknet foundry support + demonstration tests

### PR DESCRIPTION
**Pull request by 0xthomass**
PR related to issue #13

### CODE REVIEW

**Review by cloudvenger — APPROVED** [review]
Nice work 👍 

I just bump the version from `0.17.0` to `0.17.1` for foundry

**Comment by cloudvenger** [comment]
@thomas192 how much time did you take to do this PR ?

**Comment by 0xthomass** [comment]
> Nice work 👍
> 
> I just bump the version from `0.17.0` to `0.17.1` for foundry

Thanks 🙂


> @thomas192 how much time did you take to do this PR ?

I have limited experience so it took me ~2 hours. 
I also wanted to have a good grasp of what was going on, so I started reading the carbon protocol contracts this weekend (~5/6 hours over a couple days).

**Comment by tekkac** [comment]
closes #13

**Pull request merged**
